# Generated by Django 3.0.6 on 2020-06-25 16:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='Paragraph',
            field=tinymce.models.HTMLField(),
        ),
    ]
