# Generated by Django 3.0.6 on 2020-06-26 14:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200625_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='auther_bio',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='blog_auther',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='blog_quote_1',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='blog_quote_2',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='cover_img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='img_1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='img_2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='img_3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='img_4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='img_5',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='img_6',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
