# Generated by Django 3.0.6 on 2020-06-26 14:30

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('Blog', '0003_auto_20200626_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
