# Generated by Django 3.0.6 on 2020-06-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20200626_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='blog_quote_1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='blog_quote_2',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
