# Generated by Django 3.0.6 on 2020-06-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='auther_thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
