# Generated by Django 3.0.6 on 2020-06-29 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_blog_post_auther_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 23, 15, 49, 165903)),
        ),
    ]
