# Generated by Django 3.0.6 on 2020-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(max_length=30)),
                ('product_publishDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
