# Generated by Django 3.0.6 on 2020-06-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200609_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='item_subCategory',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
