# Generated by Django 3.0.6 on 2020-06-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200609_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cover',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
