# Generated by Django 3.0.6 on 2020-06-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_product_product_baneer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
