# Generated by Django 3.0.6 on 2020-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_Discount_pricse',
            field=models.FloatField(default=0.0, max_length=30),
        ),
    ]
