# Generated by Django 3.0.6 on 2020-06-10 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20200610_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promoion_id', models.AutoField(primary_key=True, serialize=False)),
                ('promotion_title', models.CharField(max_length=100)),
                ('promotion_name', models.CharField(max_length=100)),
                ('promotion_desc', models.TextField()),
                ('promotion_up_to', models.IntegerField()),
                ('promtion_cover1', models.ImageField(upload_to='')),
                ('promotion_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Product')),
                ('promotion_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Item')),
            ],
        ),
    ]
