# Generated by Django 3.0.6 on 2020-06-10 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='promotion_duration',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
