# Generated by Django 3.0.6 on 2020-06-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20200610_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_baneer',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cover',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
