# Generated by Django 3.0.6 on 2020-06-12 09:47

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20200611_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='extra_large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='extra_samll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='item_color1',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='item',
            name='item_color2',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='item',
            name='item_color3',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='item',
            name='large',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='small',
            field=models.BooleanField(default=True),
        ),
    ]
