# Generated by Django 3.0.6 on 2020-06-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20200612_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='medium',
            field=models.BooleanField(default=True),
        ),
    ]
