# Generated by Django 3.0.6 on 2020-06-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_item_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_weight',
            field=models.FloatField(default=1.0, help_text='In KG'),
        ),
    ]
