# Generated by Django 3.0.6 on 2020-06-12 17:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_item_item_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_color2',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_color3',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
    ]
