# Generated by Django 3.0.6 on 2020-06-12 17:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_auto_20200612_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_color2',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_color3',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True),
        ),
    ]
