# Generated by Django 3.0.4 on 2020-06-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_auto_20200612_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_zoom_pic1',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_zoom_pic2',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_zoom_pic3',
            field=models.ImageField(default='exit', upload_to=''),
            preserve_default=False,
        ),
    ]
