# Generated by Django 3.0.4 on 2020-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_auto_20200614_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_zoom_pic1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_zoom_pic2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_zoom_pic3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
