# Generated by Django 3.0.6 on 2020-06-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_auto_20200614_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='large',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='small',
            field=models.BooleanField(default=False),
        ),
    ]
